//! `cargo xtask <task>` — repo codegen and helpers.
//!
//! Tasks:
//! - `bindings [--check]`: export specta types from `tethys-schema` to
//!   `packages/bindings/src/generated/bindings.ts`.
//!
//! This binary is intentionally Tauri-free (pure Rust: specta only) so
//! `turbo run codegen` stays fast and needs no webview system deps.
//! Full tauri-specta command bindings (invoke signatures) are a Phase-0
//! follow-up; S0.0 generates types, `@tethys/client` wraps `invoke`.

use std::path::PathBuf;

use specta_typescript::Typescript;

fn workspace_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent() // crates
        .and_then(|p| p.parent()) // repo root
        .expect("xtask must live in <root>/crates/xtask")
        .to_path_buf()
}

fn bindings_path() -> PathBuf {
    workspace_root().join("packages/bindings/src/generated/bindings.ts")
}

fn generate() -> anyhow::Result<String> {
    let types = tethys_schema::registered_types();
    let body = Typescript::default()
        .header("// GENERATED by `cargo xtask bindings` — do not edit.\n")
        .export(&types, specta_serde::Format)?;
    Ok(body)
}

fn cmd_bindings(check: bool) -> anyhow::Result<()> {
    let out = bindings_path();
    let content = generate()?;
    if check {
        let current = std::fs::read_to_string(&out).unwrap_or_default();
        if current != content {
            anyhow::bail!("bindings out of date: run `cargo xtask bindings`");
        }
        println!("bindings up to date: {}", out.display());
        return Ok(());
    }
    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&out, content)?;
    println!("wrote {}", out.display());
    Ok(())
}

fn main() -> anyhow::Result<()> {
    let mut args = std::env::args().skip(1);
    match args.next().as_deref() {
        Some("bindings") => {
            let check = args.next().as_deref() == Some("--check");
            cmd_bindings(check)
        }
        other => {
            eprintln!("usage: cargo xtask bindings [--check]");
            if other.is_some() {
                anyhow::bail!("unknown xtask command");
            }
            Ok(())
        }
    }
}
