[package]
name = "tethys-desktop"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true

[lib]
name = "tethys_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
specta.workspace = true
tauri.workspace = true
tauri-specta.workspace = true
thiserror.workspace = true
tokio.workspace = true
tethys-api = { path = "../../../crates/tethys-api" }
tethys-core = { path = "../../../crates/tethys-core" }
tethys-schema = { path = "../../../crates/tethys-schema" }

[build-dependencies]
tauri-build = "2"
